# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('label', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission.AcademicYear')),
                ('class_level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='department.ClassLevel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.Admission')),
            ],
        ),
    ]
