# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomber', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('middle_name', models.CharField(max_length=200)),
                ('date_of_birth', models.CharField(blank=True, max_length=200, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('sexe', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Saisie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomber', models.IntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.CharField(max_length=200)),
                ('place_of_birth', models.CharField(max_length=100)),
                ('sexe', models.CharField(max_length=5)),
                ('filiation_one', models.CharField(max_length=200)),
                ('filiation_two', models.CharField(max_length=200)),
                ('guardian', models.CharField(max_length=100)),
                ('guardian_contact', models.CharField(max_length=100)),
                ('adresse_one', models.CharField(max_length=100)),
                ('adresse_two', models.CharField(blank=True, max_length=100, null=True)),
                ('school_origin', models.CharField(max_length=100)),
            ],
        ),
    ]
