# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='batch',
        ),
    ]
