# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_auto_20170724_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='genre',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), (None, 'Select Gender')], max_length=32),
        ),
    ]
