# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('school_slogan', models.CharField(blank=True, max_length=200, null=True)),
                ('school_adress_one', models.CharField(max_length=200)),
                ('school_adress_two', models.CharField(blank=True, max_length=200, null=True)),
                ('school_website', models.CharField(blank=True, max_length=100, null=True)),
                ('school_phone', models.CharField(max_length=50)),
                ('school_fax', models.CharField(blank=True, max_length=50, null=True)),
                ('school_email', models.CharField(blank=True, max_length=100, null=True)),
                ('school_tax_id', models.CharField(blank=True, max_length=100, null=True)),
                ('school_registry', models.CharField(blank=True, max_length=100, null=True)),
                ('school_authorization_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
