# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='department',
        ),
    ]
