# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_auto_20170726_1521'),
        ('school', '0002_remove_batch_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='department.Department'),
            preserve_default=False,
        ),
    ]
