# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mother_name',
        ),
    ]
