# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='genre',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=32),
        ),
    ]
