# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
