# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='baccalaureat',
            new_name='baccalaureat_id',
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default='1980-12-06'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), (None, 'Select Gender')], default='male', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='place_of_birth',
            field=models.CharField(default='labe', max_length=80),
            preserve_default=False,
        ),
    ]
