# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20170912_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='email_univ',
        ),
        migrations.RenameField(
            model_name='studentdetail',
            old_name='details_last_modified',
            new_name='last_modified',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id_number',
        ),
        migrations.AddField(
            model_name='baccalaureat',
            name='bac_type',
            field=models.CharField(default='science Maths', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='id_card_number',
            field=models.CharField(default='123365', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='address',
            field=models.CharField(default='kipe', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='adress_parents',
            field=models.CharField(default='yimbaya', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='email',
            field=models.CharField(default='coo@gmail.com', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='email_parent',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='marital_status',
            field=models.CharField(default='single', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='occupation',
            field=models.CharField(default='student', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='parent_phone',
            field=models.CharField(default='837382', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='phone',
            field=models.CharField(default='23344', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
