# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20170726_1510'),
        ('student', '0002_payment_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.AddField(
            model_name='student',
            name='class_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='department.ClassLevel'),
            preserve_default=False,
        ),
    ]
