# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200)),
                ('department_abreviation', models.CharField(max_length=10)),
                ('department_administator_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('room_places', models.IntegerField()),
                ('comment', models.CharField(max_length=1000)),
                ('room_code', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='department.Department')),
            ],
        ),
    ]
