# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20170726_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='department',
        ),
        migrations.AddField(
            model_name='subject',
            name='class_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.ClassLevel'),
        ),
    ]
