# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20170715_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='department_abreviation',
            new_name='abreviation',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='department_administator_name',
            new_name='administator_name',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='department_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_places',
            new_name='places',
        ),
    ]
