# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('department', '0003_auto_20170726_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ManyToManyField(to='employee.Teacher'),
        ),
    ]
